package com.cue.presentation.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006D3D)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF9AF6B8)
val md_theme_light_onPrimaryContainer = Color(0xFF00210F)
val md_theme_light_secondary = Color(0xFF4F6353)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD2E8D4)
val md_theme_light_onSecondaryContainer = Color(0xFF0D1F13)
val md_theme_light_tertiary = Color(0xFF3D6473)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC0E9FB)
val md_theme_light_onTertiaryContainer = Color(0xFF001F29)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFDF8)
val md_theme_light_onBackground = Color(0xFF191C19)
val md_theme_light_surface = Color(0xFFFBFDF8)
val md_theme_light_onSurface = Color(0xFF191C19)
val md_theme_light_surfaceVariant = Color(0xFFDDE5DB)
val md_theme_light_onSurfaceVariant = Color(0xFF414942)
val md_theme_light_outline = Color(0xFF717972)
val md_theme_light_inverseOnSurface = Color(0xFFF0F1ED)
val md_theme_light_inverseSurface = Color(0xFF2E312E)
val md_theme_light_inversePrimary = Color(0xFF7EDA9E)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006D3D)
val md_theme_light_outlineVariant = Color(0xFFC1C9C0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF7BD0FF)
val md_theme_dark_onPrimary = Color(0xFF00354A)
val md_theme_dark_primaryContainer = Color(0xFF001A27)
val md_theme_dark_onPrimaryContainer = Color(0xFF008ABB)
val md_theme_dark_secondary = Color(0xFFBCC7DE)
val md_theme_dark_onSecondary = Color(0xFF263143)
val md_theme_dark_secondaryContainer = Color(0xFF3E495D)
val md_theme_dark_onSecondaryContainer = Color(0xFFAEB9D0)
val md_theme_dark_tertiary = Color(0xFFBDC2FF)
val md_theme_dark_onTertiary = Color(0xFF131E8C)
val md_theme_dark_tertiaryContainer = Color(0xFF00055C)
val md_theme_dark_onTertiaryContainer = Color(0xFF6C77E1)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0B1326)
val md_theme_dark_onBackground = Color(0xFFDAE2FD)
val md_theme_dark_surface = Color(0xFF0B1326)
val md_theme_dark_onSurface = Color(0xFFDAE2FD)
val md_theme_dark_surfaceVariant = Color(0xFF2D3449)
val md_theme_dark_onSurfaceVariant = Color(0xFFC6C6CD)
val md_theme_dark_outline = Color(0xFF909097)
val md_theme_dark_inverseOnSurface = Color(0xFF283044)
val md_theme_dark_inverseSurface = Color(0xFFDAE2FD)
val md_theme_dark_inversePrimary = Color(0xFF00668A)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF7BD0FF)
val md_theme_dark_outlineVariant = Color(0xFF45464D)
val md_theme_dark_scrim = Color(0xFF000000)

// Surface Container Tiers (Nocturnal Clarity)
val surface_container_lowest = Color(0xFF060E20)
val surface_container_low = Color(0xFF131B2E)
val surface_container = Color(0xFF171F33)
val surface_container_high = Color(0xFF222A3D)
val surface_container_highest = Color(0xFF2D3449)

val seed = Color(0xFF7BD0FF)